apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: boilerbase-webapp-ingress-https
  namespace: boilerbase
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`super-sympa.fr`)
      kind: Rule
      services:
        - name: boilerbase-webapp-svc
          port: 80
  tls:
    secretName: boilerbase-webapp-cert-secret-tls

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: boilerbase-webapp-ingress-https
#  namespace: boilerbase
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#
#spec:
#  rules:
#    - host: super-sympa.fr
#      http:
#        paths:
#          - path: /
#            pathType: Exact
#            backend:
#              service:
#                name:  boilerbase-webapp-svc
#                port:
#                  number: 80
#  tls:
#    - secretName: boilerbase-webapp-cert-secret-tls