apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: boilerbase-webapp-ingress-https
  namespace: boilerbase
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`super-sympa.fr`)
      kind: Rule
      middlewares:
        - name: redirect-to-nonwww
          namespace: boilerbase
        - name: redirect-https
          namespace: boilerbase
      services:
        - name: boilerbase-webapp-svc
          port: 80
  tls:
    secretName: boilerbase-webapp-cert-secret-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-nonwww
  namespace: boilerbase
spec:
  redirectRegex:
    permanent: true
    regex: ^(?:https://)?(?:www\.)?(.+)
    replacement: https://${1}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: boilerbase
spec:
  redirectScheme:
    scheme: https
    permanent: true

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: boilerbase-webapp-ingress-https
#  namespace: boilerbase
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#
#spec:
#  rules:
#    - host: super-sympa.fr
#      http:
#        paths:
#          - path: /
#            pathType: Exact
#            backend:
#              service:
#                name:  boilerbase-webapp-svc
#                port:
#                  number: 80
#  tls:
#    - secretName: boilerbase-webapp-cert-secret-tls