apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: boilerbase-webapp-selfsigned-issuer
  namespace: boilerbase
spec:
  acme:
    email: boilerbase@proton.me
    server: https://acme-v02.api.letsencrypt.org/directory # production
    privateKeySecretRef:
      name: cert-manager-boilerbase-webapp-private-key # certificat
    solvers:
      - http01:
          ingress:
            class: traefik