apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boilerbase-webapp-certificate
  namespace: boilerbase
spec:
  # certificats wildcard
  dnsNames:
    - 'super-sympa.fr'

  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-boilerbase-webapp-stats #notre issuer
  # Secret pour stocker les certificats
  secretName: boilerbase-webapp-certificate-secret