apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boilerbase-webapp-certificate
  namespace: boilerbase
spec:
  secretName: boilerbase-webapp-cert-secret-tls
  dnsNames:
    - 'super-sympa.fr'
  issuerRef:
    kind: Issuer
    name: boilerbase-webapp-selfsigned-issuer