apiVersion: v1
kind: Service
metadata:
  name: boilerbase-webapp-svc
  namespace: boilerbase
spec:
  type: ClusterIP
  selector:
    app: boilerbase-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80