apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: boilerbase-webapp-certificate
  namespace: boilerbase
spec:
  # Secret pour stocker les certificats
  secretName: boilerbase-webapp-cert-secret-tls
  # certificats wildcard
  dnsNames:
    - 'super-sympa.fr'
  issuerRef:
    kind: ClusterIssuer
    name: boilerbase-webapp-selfsigned-issuer #notre issuer